spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8888
  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: service-one
#              uri: lb://SERVICE-ONE # dynamic router the service one should be the name of the service registered with eureka
#              predicates:
#                - Path=/api/v1/posts/**
#            - id: service-two
#              uri: lb://SERVICE-TWO
#              predicates:
#                - Path=/api/v1/orders/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        # Exposes the reactive environment and gateway routing tables
        include: gateway, env

server:
  port: 8765