spring:
  application:
    name: limiter-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/User/Desktop/git-local-config-repo # rate limiters rules are stored here

server:
  port:
